/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.samples.fbo.custom.notification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CustomNotification service. Represents a row in the &quot;FBO_CustomNotification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.samples.fbo.custom.notification.model.impl.CustomNotificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.samples.fbo.custom.notification.model.impl.CustomNotificationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomNotification
 * @generated
 */
@ProviderType
public interface CustomNotificationModel
	extends BaseModel<CustomNotification>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom notification model instance should use the {@link CustomNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this custom notification.
	 *
	 * @return the primary key of this custom notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom notification.
	 *
	 * @param primaryKey the primary key of this custom notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this custom notification.
	 *
	 * @return the uuid of this custom notification
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this custom notification.
	 *
	 * @param uuid the uuid of this custom notification
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the custom notification ID of this custom notification.
	 *
	 * @return the custom notification ID of this custom notification
	 */
	public long getCustomNotificationId();

	/**
	 * Sets the custom notification ID of this custom notification.
	 *
	 * @param customNotificationId the custom notification ID of this custom notification
	 */
	public void setCustomNotificationId(long customNotificationId);

	/**
	 * Returns the company ID of this custom notification.
	 *
	 * @return the company ID of this custom notification
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this custom notification.
	 *
	 * @param companyId the company ID of this custom notification
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this custom notification.
	 *
	 * @return the user ID of this custom notification
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this custom notification.
	 *
	 * @param userId the user ID of this custom notification
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this custom notification.
	 *
	 * @return the user uuid of this custom notification
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this custom notification.
	 *
	 * @param userUuid the user uuid of this custom notification
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this custom notification.
	 *
	 * @return the user name of this custom notification
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this custom notification.
	 *
	 * @param userName the user name of this custom notification
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this custom notification.
	 *
	 * @return the create date of this custom notification
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this custom notification.
	 *
	 * @param createDate the create date of this custom notification
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this custom notification.
	 *
	 * @return the modified date of this custom notification
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this custom notification.
	 *
	 * @param modifiedDate the modified date of this custom notification
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user notification event ID of this custom notification.
	 *
	 * @return the user notification event ID of this custom notification
	 */
	public long getUserNotificationEventId();

	/**
	 * Sets the user notification event ID of this custom notification.
	 *
	 * @param userNotificationEventId the user notification event ID of this custom notification
	 */
	public void setUserNotificationEventId(long userNotificationEventId);

	/**
	 * Returns the notification type of this custom notification.
	 *
	 * @return the notification type of this custom notification
	 */
	@AutoEscape
	public String getNotificationType();

	/**
	 * Sets the notification type of this custom notification.
	 *
	 * @param notificationType the notification type of this custom notification
	 */
	public void setNotificationType(String notificationType);

}